/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.lxh.myzngt.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.lxh.myzngt.dao.IUserDAO;
import org.lxh.myzngt.struts.form.AdminuserForm;

/**
 * MyEclipse Struts Creation date: 07-03-2007
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/adminuser" name="adminuserForm"
 *                input="/form/adminuser.jsp" parameter="status" scope="request"
 *                validate="true"
 */
public class AdminuserAction extends DispatchAction {
	private IUserDAO iuserdao = null;

	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward list(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List all = null;
		int currentPage = 1;
		int lineSize = 10;
		int allRecorders = 0;
		try {
			currentPage = Integer.parseInt(request.getParameter("cp"));
		} catch (Exception e) {
		}
		try {
			allRecorders = this.iuserdao.getAllCount();
			all = this.iuserdao.queryAll(currentPage, lineSize);
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		request.setAttribute("currentPage", currentPage);
		request.setAttribute("lineSize", lineSize);
		request.setAttribute("allRecorders", allRecorders);
		request.setAttribute("all", all);
		request.setAttribute("jspUrl", "adminuser.do");
		request.setAttribute("status", "list");
		return mapping.findForward("userlist");
	}

	public ActionForward updateIntegral(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdminuserForm adminuserForm = (AdminuserForm) form;
		try {
			this.iuserdao.updateIntegral(adminuserForm.getUserid(), Integer
					.parseInt(adminuserForm.getIntegral()));
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return mapping.findForward("list");
	}

	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdminuserForm adminuserForm = (AdminuserForm) form;
		try {
			this.iuserdao.delete(adminuserForm.getUserid());
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return mapping.findForward("list");
	}

	public IUserDAO getIuserdao() {
		return iuserdao;
	}

	public void setIuserdao(IUserDAO iuserdao) {
		this.iuserdao = iuserdao;
	}
}