/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.lxh.myzngt.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.lxh.myzngt.dao.IItemDAO;
import org.lxh.myzngt.dao.ISubitemDAO;
import org.lxh.myzngt.struts.form.AdminsubitemForm;
import org.lxh.myzngt.vo.Item;
import org.lxh.myzngt.vo.Subitem;

/**
 * MyEclipse Struts Creation date: 07-03-2007
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/adminsubitem" name="adminsubitemForm"
 *                input="/form/adminsubitem.jsp" parameter="status"
 *                scope="request" validate="true"
 */
public class AdminsubitemAction extends DispatchAction {
	private ISubitemDAO isubitemdao;

	private IItemDAO iitemdao;

	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdminsubitemForm adminsubitemForm = (AdminsubitemForm) form;
		Subitem sub = new Subitem();
		sub.setSubname(adminsubitemForm.getSubname());
		sub.setSubcode(Integer.parseInt(adminsubitemForm.getSubcode()));
		Item item = new Item();
		item.setItemid(Integer.parseInt(adminsubitemForm.getItemid()));
		sub.setItem(item);
		try {
			this.isubitemdao.insert(sub);
			request.setAttribute("item", this.iitemdao.queryById(item
					.getItemid()));
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return mapping.findForward("subitemlist");
	}

	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdminsubitemForm adminsubitemForm = (AdminsubitemForm) form;
		try {
			this.isubitemdao.delete(Integer.parseInt(adminsubitemForm
					.getSubid()));
			request.setAttribute("item", this.iitemdao.queryById(Integer
					.parseInt(adminsubitemForm.getItemid())));
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return mapping.findForward("subitemlist");
	}

	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdminsubitemForm adminsubitemForm = (AdminsubitemForm) form;
		Subitem sub = new Subitem();
		sub.setSubid(Integer.parseInt(adminsubitemForm.getSubid()));
		sub.setSubname(adminsubitemForm.getSubname());
		sub.setSubcode(Integer.parseInt(adminsubitemForm.getSubcode()));
		try {
			this.isubitemdao.update(sub);
			request.setAttribute("item", this.iitemdao.queryById(Integer
					.parseInt(adminsubitemForm.getItemid())));
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return mapping.findForward("subitemlist");
	}

	public ISubitemDAO getIsubitemdao() {
		return isubitemdao;
	}

	public void setIsubitemdao(ISubitemDAO isubitemdao) {
		this.isubitemdao = isubitemdao;
	}

	public IItemDAO getIitemdao() {
		return iitemdao;
	}

	public void setIitemdao(IItemDAO iitemdao) {
		this.iitemdao = iitemdao;
	}
}