/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.lxh.myzngt.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.DispatchAction;
import org.lxh.myzngt.dao.IQuestionDAO;

/**
 * MyEclipse Struts Creation date: 07-03-2007
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/adminquestion" name="adminquestionForm"
 *                input="/form/adminquestion.jsp" parameter="status"
 *                scope="request" validate="true"
 */
public class AdminquestionAction extends DispatchAction {
	private IQuestionDAO iquestiondao;

	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward commen(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionForm adminquestionForm = (DynaActionForm) form;
		int qid = Integer.parseInt(request.getParameter("qid")) ;
		int commen = Integer.parseInt(request.getParameter("commen")) ;
		try {
			this.iquestiondao.updateCommen(qid, commen) ;
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return mapping.findForward("list");
	}

	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionForm adminquestionForm = (DynaActionForm) form;
		int qid = Integer.parseInt(request.getParameter("qid")) ;
		try {
			this.iquestiondao.delete(qid) ;
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return mapping.findForward("list");
	}

	public ActionForward list(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List all = null;
		int currentPage = 1;
		int lineSize = 10;
		int allRecorders = 0;
		try {
			currentPage = Integer.parseInt(request.getParameter("cp"));
		} catch (Exception e) {
		}
		try {
			allRecorders = this.iquestiondao.getAllCount();
			all = this.iquestiondao.queryAll(currentPage, lineSize);
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		request.setAttribute("currentPage", currentPage);
		request.setAttribute("lineSize", lineSize);
		request.setAttribute("allRecorders", allRecorders);
		request.setAttribute("all", all);
		request.setAttribute("jspUrl", "adminquestion.do");
		request.setAttribute("status", "list");
		return mapping.findForward("questionlist");
	}

	public IQuestionDAO getIquestiondao() {
		return iquestiondao;
	}

	public void setIquestiondao(IQuestionDAO iquestiondao) {
		this.iquestiondao = iquestiondao;
	}
}