/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.lxh.myzngt.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.DispatchAction;
import org.lxh.myzngt.dao.IItemDAO;
import org.lxh.myzngt.dao.IQuestionDAO;

/**
 * MyEclipse Struts Creation date: 07-02-2007
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/index" name="indexForm" input="/form/index.jsp"
 *                parameter="status" scope="request" validate="true"
 */
public class IndexAction extends DispatchAction {
	// 需要取栏目和各种问题
	private IItemDAO iitemdao;

	private IQuestionDAO iquestiondao;

	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward list(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionForm indexForm = (DynaActionForm) form;
		// 查询信息
		List allitem = null ;
		List allcommen = null ;
		List status1 = null ;
		List status2 = null ;
		try {
			allitem = this.iitemdao.queryAll() ;
			allcommen = this.iquestiondao.queryByCommemflag(1, 1, 2) ;
			status1 = this.iquestiondao.queryByStatus(1, 1, 8) ;
			status2 = this.iquestiondao.queryByStatus(2, 1, 8) ;
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		request.setAttribute("allitem", allitem) ;
		request.setAttribute("allcommen", allcommen) ;
		request.setAttribute("status1", status1) ;
		request.setAttribute("status2", status2) ;
		return mapping.findForward("indexdo");
	}

	public IItemDAO getIitemdao() {
		return iitemdao;
	}

	public void setIitemdao(IItemDAO iitemdao) {
		this.iitemdao = iitemdao;
	}

	public IQuestionDAO getIquestiondao() {
		return iquestiondao;
	}

	public void setIquestiondao(IQuestionDAO iquestiondao) {
		this.iquestiondao = iquestiondao;
	}
}