/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.lxh.myzngt.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 07-03-2007
 * 
 * XDoclet definition:
 * @struts.form name="adminloginForm"
 */
public class AdminloginForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** adminpwd property */
	private String adminpwd;

	/** adminid property */
	private String adminid;
	
	private String checkcode ;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = null ;
			if (this.adminid == null || "".equals(this.adminid)) {
				errors.add("adminid", new ActionMessage("admin.adminid.null"));
			}
			if (this.adminpwd == null || "".equals(this.adminpwd)) {
				errors.add("adminid", new ActionMessage("admin.adminpwd.null"));
			}
			if (this.checkcode == null || "".equals(this.checkcode)) {
				errors.add("checkcode", new ActionMessage("checkcode.null"));
			}
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the adminpwd.
	 * @return String
	 */
	public String getAdminpwd() {
		return adminpwd;
	}

	/** 
	 * Set the adminpwd.
	 * @param adminpwd The adminpwd to set
	 */
	public void setAdminpwd(String adminpwd) {
		this.adminpwd = adminpwd;
	}

	/** 
	 * Returns the adminid.
	 * @return String
	 */
	public String getAdminid() {
		return adminid;
	}

	/** 
	 * Set the adminid.
	 * @param adminid The adminid to set
	 */
	public void setAdminid(String adminid) {
		this.adminid = adminid;
	}

	public String getCheckcode() {
		return checkcode;
	}

	public void setCheckcode(String checkcode) {
		this.checkcode = checkcode;
	}
}