/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.lxh.myzngt.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-03-2007
 * 
 * XDoclet definition:
 * @struts.form name="adminsubitemForm"
 */
public class AdminsubitemForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** subid property */
	private String subid;

	/** subname property */
	private String subname;

	/** itemid property */
	private String itemid;

	/** subcode property */
	private String subcode;

	private int type ;
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the subid.
	 * @return String
	 */
	public String getSubid() {
		return subid;
	}

	/** 
	 * Set the subid.
	 * @param subid The subid to set
	 */
	public void setSubid(String subid) {
		this.subid = subid;
	}

	/** 
	 * Returns the subname.
	 * @return String
	 */
	public String getSubname() {
		return subname;
	}

	/** 
	 * Set the subname.
	 * @param subname The subname to set
	 */
	public void setSubname(String subname) {
		this.subname = subname;
	}

	/** 
	 * Returns the itemid.
	 * @return String
	 */
	public String getItemid() {
		return itemid;
	}

	/** 
	 * Set the itemid.
	 * @param itemid The itemid to set
	 */
	public void setItemid(String itemid) {
		this.itemid = itemid;
	}

	/** 
	 * Returns the subcode.
	 * @return String
	 */
	public String getSubcode() {
		return subcode;
	}

	/** 
	 * Set the subcode.
	 * @param subcode The subcode to set
	 */
	public void setSubcode(String subcode) {
		this.subcode = subcode;
	}
}