/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.lxh.myzngt.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/**
 * MyEclipse Struts Creation date: 07-01-2007
 * 
 * XDoclet definition:
 * 
 * @struts.form name="answerForm"
 */
public class AnswerForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** qid property */
	private String qid;

	/** anstime property */
	private String anstime;

	/** userid property */
	private String userid;

	/** quesans property */
	private String quesans;

	/** aid property */
	private String aid;

	/** status property */
	private String status;

	/** grade property */
	private String grade;

	private String checkcode;

	private int type;

	// 1：表示增加回答

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		if (type == 1) {
			if (this.checkcode == null || "".equals(this.checkcode)) {
				errors.add("checkcode", new ActionMessage("checkcode.null"));
			}
			if (this.quesans == null || "".equals(this.quesans)) {
				errors.add("quesans", new ActionMessage("answer.quesans.null"));
			}
			if (this.qid == null || "".equals(this.qid)) {
				errors.add("qid",new ActionMessage("")) ;
			}
		}
		return errors;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the qid.
	 * 
	 * @return String
	 */
	public String getQid() {
		return qid;
	}

	/**
	 * Set the qid.
	 * 
	 * @param qid
	 *            The qid to set
	 */
	public void setQid(String qid) {
		this.qid = qid;
	}

	/**
	 * Returns the anstime.
	 * 
	 * @return String
	 */
	public String getAnstime() {
		return anstime;
	}

	/**
	 * Set the anstime.
	 * 
	 * @param anstime
	 *            The anstime to set
	 */
	public void setAnstime(String anstime) {
		this.anstime = anstime;
	}

	/**
	 * Returns the userid.
	 * 
	 * @return String
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * Set the userid.
	 * 
	 * @param userid
	 *            The userid to set
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * Returns the quesans.
	 * 
	 * @return String
	 */
	public String getQuesans() {
		return quesans;
	}

	/**
	 * Set the quesans.
	 * 
	 * @param quesans
	 *            The quesans to set
	 */
	public void setQuesans(String quesans) {
		this.quesans = quesans;
	}

	/**
	 * Returns the aid.
	 * 
	 * @return String
	 */
	public String getAid() {
		return aid;
	}

	/**
	 * Set the aid.
	 * 
	 * @param aid
	 *            The aid to set
	 */
	public void setAid(String aid) {
		this.aid = aid;
	}

	/**
	 * Returns the status.
	 * 
	 * @return String
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * Set the status.
	 * 
	 * @param status
	 *            The status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Returns the grade.
	 * 
	 * @return String
	 */
	public String getGrade() {
		return grade;
	}

	/**
	 * Set the grade.
	 * 
	 * @param grade
	 *            The grade to set
	 */
	public void setGrade(String grade) {
		this.grade = grade;
	}

	public String getCheckcode() {
		return checkcode;
	}

	public void setCheckcode(String checkcode) {
		this.checkcode = checkcode;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}
}